Update Dockerfile

diff --git a/packages/api/Dockerfile b/packages/api/Dockerfile
--- a/packages/api/Dockerfile
+++ b/packages/api/Dockerfile
@@ -5,6 +5,7 @@ COPY prisma ./prisma/
 RUN npm install
 COPY . .
 RUN npx prisma generate
-RUN npx tsc --skipLibCheck --module commonjs --moduleResolution node --target ES2020 --outDir ./dist --esModuleInterop --resolveJsonModule --lib ES2020
+RUN npx tsc --skipLibCheck --module commonjs --moduleResolution node --target ES2020 --outDir ./dist --esModuleInterop --resolveJsonModule --lib ES2020 || echo "TSC failed"
+RUN ls -la dist/ || echo "dist empty"
 EXPOSE 3001
 CMD ["node", "dist/index.js"]
